language: node_js
node_js: node
notifications:
  email: false
install:
  - yarn install
jobs:
  include:
    - stage: "Lint and Test"
      name: "Lint"
      script: yarn lint
    - script: yarn test
      name: "Test"
    - stage: Build
      script: yarn generate
    - stage: Deploy
      script: yarn generate:gh-pages
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep_history: true
        local_dir: dist
        on:
          branch: master
stages:
  - "Lint and Test"
  - "Build"
  - name: Deploy
    if: branch = master